repos:
-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
        language_version: python3
        args: ["--check", "src"]
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: uv-build
        name: uv-build
        entry: uv build
        language: system
        pass_filenames: false
        always_run: true